"""empty message

Revision ID: 185574d66b2b
Revises: 4ffbd0bc07c4
Create Date: 2022-08-10 17:37:25.404939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185574d66b2b'
down_revision = '4ffbd0bc07c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('send', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'send')
    # ### end Alembic commands ###
