"""empty message

Revision ID: 310246ab3550
Revises: 8040a7b6cd0d
Create Date: 2022-09-01 18:54:38.446717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310246ab3550'
down_revision = '8040a7b6cd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('pdf', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'pdf')
    # ### end Alembic commands ###
