"""empty message

Revision ID: 48dabec5112f
Revises: 53a97f273ef4
Create Date: 2022-08-14 15:03:14.339329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dabec5112f'
down_revision = '53a97f273ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donate', sa.Column('biggest_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donate', 'biggest_amount')
    # ### end Alembic commands ###
