"""empty message

Revision ID: 4ffbd0bc07c4
Revises: 34ff9366b152
Create Date: 2022-08-10 16:29:02.447655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffbd0bc07c4'
down_revision = '34ff9366b152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donate', sa.Column('donation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'donate', 'donation', ['donation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donate', type_='foreignkey')
    op.drop_column('donate', 'donation_id')
    # ### end Alembic commands ###
