"""empty message

Revision ID: 53a97f273ef4
Revises: 185574d66b2b
Create Date: 2022-08-14 13:43:54.995100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a97f273ef4'
down_revision = '185574d66b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donate', sa.Column('total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donate', 'total')
    # ### end Alembic commands ###
