"""empty message

Revision ID: 8040a7b6cd0d
Revises: 48dabec5112f
Create Date: 2022-08-16 18:48:28.579147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '8040a7b6cd0d'
down_revision = '48dabec5112f'
branch_labels = None
depends_on = None


def upgrade():
    donatorsrewards = postgresql.ENUM('novice', 'normal', 'super', 'elite', 'vip', 'legendary', 'mythic', name='donatorsrewards')
    donatorsrewards.create(op.get_bind())
    op.add_column('users', sa.Column('donator_status', sa.Enum('novice', 'normal', 'super', 'elite', 'vip', 'legendary', 'mythic', name='donatorsrewards'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'donator_status')
    # ### end Alembic commands ###
