"""empty message

Revision ID: 80a2a75a1449
Revises: 77e8f88dfeb1
Create Date: 2022-08-08 18:00:44.734787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80a2a75a1449'
down_revision = '77e8f88dfeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('received_money', sa.Float(), nullable=False))
    op.drop_column('donation', 'received')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('received', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('donation', 'received_money')
    # ### end Alembic commands ###
